name: Make Keystore (run once)
on: workflow_dispatch
jobs:
  ks:
    runs-on: ubuntu-latest
    steps:
      - run: |
          keytool -genkeypair -keystore debug.keystore -storepass android -keypass android -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Al Itqan Store"
          base64 -w 0 debug.keystore > keystore_b64.txt
      - uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore_b64.txt
